version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:5000
    depends_on:
      mongodb:
        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "http://localhost:5000/api/v1/monitoring/status/health"]
#      timeout: 120s
#      interval: 120s
#      retries: 3
#      start_period: 120s
#    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongo", "--eval", "printjson(db.runCommand({ping: 1}))"]
      timeout: 10s
      interval: 10s
      retries: 3
      start_period: 5s
    restart: always
